version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.10.0-browsers
    working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          command: |
            mkdir -p test-results/jest

#            TEST=$(circleci tests glob src/**/*.test.js | circleci tests split --split-by=timings)
#            yarn test:ci $TEST
            yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
